services:
  scholar-api:
    container_name: scholar-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    networks:
      - nestjs-app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    user: node
    depends_on:
       - postgres
       - redis
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - nestjs-app
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - nestjs-app
volumes:
  postgres:
  redis:
    driver: local
networks:
  nestjs-app:
    driver: bridge
