services:
  scholar-api:
    container_name: scholar-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    networks:
      - nestjs-app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    user: node
    depends_on:
       - postgres
       - redis
       - minio
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - nestjs-app
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - nestjs-app
  minio:
    container_name: minio
    image: docker.io/bitnami/minio:2022
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: supersecret
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - nestjs-app
    volumes:
      - 'minio:/data'
volumes:
  postgres:
  redis:
    driver: local
  minio:
    driver: local
networks:
  nestjs-app:
    driver: bridge
